### ISSUE TITLE
weight and height empty

### ISSUE THREAD

**Issue by davidanaya** [krokyze/FitKit#16]
Hi,

Thanks for the plugin, it's awesome.

I tested it both with Android and iOS builds and works fine but I can't get any value for Height and Weight. I have it both in Apple Health and Google Fit and I'm reading it with the `readAll` method. Is this supposed to work? As they are not values within a period of time maybe I need to do it with `read` only?

**Comment by davidanaya** [comment]
I was reading the values from the last 5 days and weight and height are not returned unless I update the values.
I guess this should not be like that, we should get a proper reading for weight and height even if the values have not been updated in the last 5 days.

**Comment by krokyze** [comment]
Hey, so currently how this plugin works is reading data types within a period of time. Completely understand your point of view and will add this as a feature request to support reading last value of any data type.

**Comment by davidanaya** [comment]
Thanks @krokyze

**Comment by krokyze** [comment]
Let's just leave it open, once it's in the plugin I will close it ;)

**Comment by krokyze** [comment]
In version 1.0.0 new parameter `readLast` has been implemented.
