### ISSUE TITLE
Got the permission, but every array is empty, when it reads the data.

### ISSUE THREAD

**Issue by janosdupai** [krokyze/FitKit#21]
Thank you for this awesome pub!
I implemented it, and everything works fine in iOS, but somehow android device give me empty arrays, without any data.
If I am right, I got the permission, and the console printing me every datatype, but it has an empty square bracket.
Should I do any specific on android devices?
My application not appears in the device setting at the Samsung Health Settings -> connected services (where my fitness apps are - that apps also using the samsung health data too).

**Comment by janosdupai** [comment]
D/FitKit  (21469): readSample: heart_rate
I/flutter (21469): []
D/FitKit  (21469): readSample: step_count
I/flutter (21469): []
D/FitKit  (21469): readSample: height
I/flutter (21469): []
D/FitKit  (21469): readSample: weight
I/flutter (21469): []
D/FitKit  (21469): readSample: distance
I/flutter (21469): []
D/FitKit  (21469): readSample: energy
I/flutter (21469): []
D/FitKit  (21469): readSample: water
I/flutter (21469): []
D/FitKit  (21469): readSample: sleep
I/flutter (21469): []

**Comment by krokyze** [comment]
Hey @janosdupai Android is integrated with Google Fit, as far as I know they don't have any connection between them. Can you please try to [sync your Samsung Health Data with Google Fit](https://www.androidauthority.com/sync-samsung-health-google-fit-870718/)?

**Comment by janosdupai** [comment]
Thank you! That was the reason. Now works perfectly!
