### ISSUE TITLE
Duplicates the AppleWatch and devices data on iOS

### ISSUE THREAD

**Issue by janosdupai** [krokyze/FitKit#22]
The apple health stores the energy, steps, and distance data.

The apple health shows, that my Watch stored 12500 steps, and the device tracked 12200. But fit_kit cumulates the data, and I get a result of 24700. Can we make difference somehow among the data sources?

**Comment by krokyze** [comment]
Hey, now in the 0.0.6 version FitData has extra field source, that should solve your issue.

**Comment by melsheikh92** [comment]
@krokyze is there a way to get the summary value as in the Health app on iOS without calculating steps overlaps which will not be accurate.
