### ISSUE TITLE
App crashes when installed..and exitis abruptly while performing function readall

### ISSUE THREAD

**Issue by thevishvajeet** [krokyze/FitKit#23]

**Comment by krokyze** [comment]
Hey sorry to hear that, is that the new version 0.0.6 or previous 0.0.5 too? Which platform Android/iOS? Can you give some stacktrace please?

**Comment by brightboahen** [comment]
I'm having the same issue with version **^0.0.6** on iOS

**Comment by brightboahen** [comment]
@thevishvajeet - I was having the same issue but realised I hadn't added the capabilities to the plist.
