### ISSUE TITLE
How to ignore data that was manually entered by users in HealthKit/GoogleFit?

### ISSUE THREAD

**Issue by SheriefAlaa** [krokyze/FitKit#26]
Hi Martin / @krokyze,

I was wondering whether it is possible or not filter out data by manual entry as false. I see that iOS has a [metakey](https://developer.apple.com/documentation/healthkit/hkmetadatakeywasuserentered) for this, but I am not sure about Android.

Any help would be appreciated.

Thanks.

-Sherief

**Comment by SheriefAlaa** [comment]
I see it's also [possible](https://developers.google.com/android/reference/com/google/android/gms/fitness/data/DataSource.html#TYPE_RAW) for Android/Google Fitness

**Comment by krokyze** [comment]
Hey `userEntered` has been added in version 1.0.1. 😉

**Comment by DonsWayo** [comment]
where I need to add this userEntered parameter?, can you provide a example?

`var results = await FitKit.read(
      DataType.STEP_COUNT,
      dateFrom: fromDay,
      dateTo: DateTime.now(),
    );
`

Thanks!

**Comment by krokyze** [comment]
> where I need to add this userEntered parameter?, can you provide a example?
> 
> `var results = await FitKit.read( DataType.STEP_COUNT, dateFrom: fromDay, dateTo: DateTime.now(), ); `
> 
> Thanks!

Hey `userEntered` is returned for every FitData object. So you can just filter them out from results.
https://github.com/krokyze/FitKit/blob/16719c3be3554eec1ac61f4e01d4b9a6df7b92a1/lib/src/fit_data.dart#L15

**Comment by DonsWayo** [comment]
okay perfect, Thanks for the library!
