### ISSUE TITLE
Kotlin version issue

### ISSUE THREAD

**Issue by UwaisWisitech** [krokyze/FitKit#3]
What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':fit_kit' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by krokyze** [comment]
Fixed in v0.0.4.

**Comment by krokyze** [comment]
Fixed in v0.0.4.
