### ISSUE TITLE
Users are able to get past the google read activity prompt

### ISSUE THREAD

**Issue by SheriefAlaa** [krokyze/FitKit#31]
Hi @krokyze,

I use in my app `FitKit.requestPermissions([DataType.DISTANCE])` but if a user taps outside of the google prompt, I can never trigger it back and sometimes I get:
`PlatformException(FitKit, 4: The user must be signed in to make this API call., null)`

Is there any way I can re-trigger the google prompt?

Thanks.

**Comment by krokyze** [comment]
Hey @SheriefAlaa 

Tried to reproduce this in example app but unsuccessfully. Can you please share your code here?
