### ISSUE TITLE
Running example app is extremely difficult

### ISSUE THREAD

**Issue by HarisSpahija** [krokyze/FitKit#32]
As someone who is new to using google fit in flutter it is particularly hard to run the example app. A lot is either missing or just wrong such as the dependency of `fit_kit` in `pubspec.yaml`

Could there be some more instructions added to the `README.md` on how to make the example run? Thanks! 

@krokyze If you need help feel free to let us know so we can submit a PR

**Comment by krokyze** [comment]
Hey @HarisSpahija 

Could you please name all the issues you had trouble with? Submitting step by step in a PR would definitely help me.

About the dependency then it's correct. You should clone the whole project.

**Comment by HarisSpahija** [comment]
This was a bit how my process went trying to test the example app

```
1. I cloned the example folder
2. Flutter run gave me an error that fit_kit was undefined
3. Changed fit_kit in pubspec.yaml
4. Received no data in the example app
5. Had to create a google oAuth2 token
6. Add items to gradle according to the Google Fit instructions
7. Rebuild the app
8. Finally got the app to work
```

I think having a simple instructions guide or warning with:

```
You need to get a oauth2 key before you can run this app. 
Clone the entire project for running the example app etc. 
```

Having this would already be super helpful for new users for this library.

**Comment by jaydeep42** [comment]
@HarisSpahija  what items you added in gradle?
Because I am still getting 0 in all the data

**Comment by L3thal14** [comment]
@jaydeep42 Just add google-services.json with oauth2 ID generated and in build.gradle under dependencies add these 2:
` compile 'com.google.android.gms:play-services-fitness:18.0.0' `
` compile 'com.google.android.gms:play-services-auth:17.0.0' `
Happy Fluttering! :))

**Comment by gokulp01** [comment]
@L3thal14 thanks. That worked :)

**Comment by HarisSpahija** [comment]
I think this issue can be closed with the comments from @L3thal14
