### ISSUE TITLE
requestCode too big.

### ISSUE THREAD

**Issue by zbolo-wd** [krokyze/FitKit#35]
FitKit/android/src/main/kotlin/com/example/fit_kit/FitKitPlugin.kt

45 |        private const val GOOGLE_FIT_REQUEST_CODE = 80085

Did I miss something or is there a way to set it up differently?

**Comment by krokyze** [comment]
Hey never had issues like this, but just understood it's actually too big. Will change it this evening and push a new version 😉

**Comment by krokyze** [comment]
Fix released in version 1.1.1 😉

**Comment by zbolo-wd** [comment]
Thanks man ;)
