### ISSUE TITLE
Google account selection dialog is prompting every time when FitKit.requestPermissions is being called on Android.

### ISSUE THREAD

**Issue by kwanso-ahsan** [krokyze/FitKit#45]
@krokyze 
![20200430_151729](https://user-images.githubusercontent.com/41280513/80699761-f88f8f80-8af5-11ea-8a51-1fc602a2f964.png)

**Comment by kwanso-ahsan** [comment]
@krokyze Can you please address this issue?

**Comment by LaxmikanthMadhyastha** [comment]
Any update on this?

**Comment by vvicenteboo** [comment]
i have same issue, on dev is working well but on release is prompting google account selection every time with requestPermissions result false, any solution?

**Comment by LaxmikanthMadhyastha** [comment]
Hi, any update regarding this issue?

**Comment by krokyze** [comment]
I'm not 100% sure what could lead to this issue. Can you make sure that for the client ID you added release SHA-1 and not the debug one? @vvicenteboo

**Comment by LaxmikanthMadhyastha** [comment]
Hi @krokyze, I have checked the SHA-1 fingerprint and it is of release one.
When I tried with flutter run --release also it is working fine but only when the app is downloaded from play store dialog is prompting every time even after giving the permission.

**Comment by krokyze** [comment]
@LaxmikanthMadhyastha it sounds like you have enabled App signing in Google Play and your upload, signing certificates are different. You need to add the signing SHA-1 which you can find in Google Play Console -> Your app -> Release management -> App signing.

**Comment by LaxmikanthMadhyastha** [comment]
@krokyze Thanks a lot it worked, that's a new thing which I didn't know

**Comment by krokyze** [comment]
@LaxmikanthMadhyastha happy to hear that! 😉
