### ISSUE TITLE
Apple HealthKit data types

### ISSUE THREAD

**Issue by PaNaVTEC** [krokyze/FitKit#5]
Hi,

I was wondering if there is any plan to support the data types that Apple supports even if they are not supported by google fit:

https://developer.apple.com/documentation/healthkit/data_types

For example, 
```
static let waistCircumference: HKQuantityTypeIdentifier
```

Thanks.

**Comment by krokyze** [comment]
Hey @PaNaVTEC 

Yes definitely, I just currently haven't decided how to handle unsupported data types and had time to do it, so if you're interested you can definitely make a pull request ;)

**Comment by PaNaVTEC** [comment]
@krokyze  I can take a look on how to implement it, do you have any idea/preference? I was thinking on returning something like an `Option<T>`, so if we publish all the possible datatypes it can return `Some(measure)` or `Nothing`.

**Comment by krokyze** [comment]
Hey @PaNaVTEC

Sorry for the late reply. Yes Optional sounds like the right choice. I will close this issue, feel free to open new one ;)
