### ISSUE TITLE
Missing Fitness Access popup

### ISSUE THREAD

**Issue by troyzonzon** [krokyze/FitKit#54]
Hi I have used your widget in other apps, but this particular app using the newest widget is not popping up the authorization screen, I am only seeing the account selection.

**Comment by krokyze** [comment]
Hey @troyzonzon could you be more specific. Android or iOS? Which version?

**Comment by ltonn02** [comment]
Hi, I have the same problem with my app. I'm using the Android version. Every time I start the app the account selector pops up, when I click on my account nothing happens. When I try to read data using this:

`final results = await FitKit.read(`
`      DataType.DISTANCE,`
`      dateFrom: DateTime.now().subtract(Duration(days: 5)),`
`      dateTo: DateTime.now(),`
 `   );`

I get this error:
`PlatformException (PlatformException(FitKit, User denied permission access, null))`

**Comment by krokyze** [comment]
@ltonn02 can you please verify this: https://github.com/krokyze/FitKit/issues/45#issuecomment-643667079

**Comment by ltonn02** [comment]
@krokyze thanks for your advice, I think I fixed the issue. You need to add the release SHA-1 to the debug configuration as well.
My build.gradle now looks like this:

![signingconfig](https://user-images.githubusercontent.com/40540600/86619012-2099e400-bfba-11ea-86ea-e0cf546c762d.png)

![buildtypes](https://user-images.githubusercontent.com/40540600/86619081-37403b00-bfba-11ea-95ab-40d30f4b8f14.png)
