### ISSUE TITLE
[Android] infinite loading after choose account in OAuth consent screen

### ISSUE THREAD

**Issue by nongtiny** [krokyze/FitKit#69]
Flutter 1.22.5 • channel stable
fit_kit: ^1.1.2
ONEPLUS A6000

When I checked the permission in the application info, the physical activity is allowed, but it can't use `FitKit.read`.

**Comment by nagisayuu** [comment]
I had same issue.
In my case , making the Publishing status "In production" in oauth concent screen setting solved the issue.

https://console.developers.google.com/apis/

**Comment by Harshdeep4295** [comment]
Edited: if you want to use it in the testing state, do add a user who will have access to the GCP by adding a test user. 
as displayed in image.
<img width="697" alt="Screenshot 2021-01-19 at 8 52 05 PM" src="https://user-images.githubusercontent.com/25767941/105054601-32dff900-5a98-11eb-87ff-1d2742f0cc47.png">

**Comment by nongtiny** [comment]
I changed to the production state, and it works. Before that, I did like what you do @Harshdeep4295, and it also works.

Right now, I don't know why it works only in the production state.

By the way, thank you for your responses.
